//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
// File: ModelController.cpp
//
// MATLAB Coder version            : 5.2
// C/C++ source code generated on  : 06-Aug-2021 10:18:26
//

// Include Files
#include "ModelController.h"

// Function Definitions
//
// Arguments    : void
// Return Type  : void
//
ModelController::ModelController()
{
}

//
// Arguments    : void
// Return Type  : void
//
ModelController::~ModelController()
{
  // (no terminate code required)
}

//
// B_STATE_LIM_CALC
//     B_STATE_LIM =
//     B_STATE_LIM_CALC(BETA_LB,BETA_UB,BETA,BETA_DOT,DELTA,PHI_R,PHI_R_LB,PHI_R_UB,PHI_R_DOT)
//     This function was generated by the Symbolic Math Toolbox version 8.7.
//     29-Jul-2021 16:01:09
//
// Arguments    : double delta
//                const double phi_r_lim[2]
//                const double beta_lim[2]
//                double phi_r
//                double beta
//                double phi_r_dot
//                double beta_dot
//                double b_state_lim[4]
// Return Type  : void
//
void ModelController::b_state_lim_calc(double delta, const double phi_r_lim[2],
                                       const double beta_lim[2], double phi_r,
                                       double beta, double phi_r_dot,
                                       double beta_dot, double b_state_lim[4])
{
  double t2;
  double t3;
  t2 = beta_dot * delta;
  t3 = delta * phi_r_dot;
  b_state_lim[0] = (-phi_r + phi_r_lim[1]) - t3;
  b_state_lim[1] = (beta_lim[1] - beta) - t2;
  b_state_lim[2] = (phi_r + phi_r_lim[0]) + t3;
  b_state_lim[3] = (beta_lim[0] + beta) + t2;
}

//
// File trailer for ModelController.cpp
//
// [EOF]
//
