//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
// File: ModelController.cpp
//
// MATLAB Coder version            : 5.2
// C/C++ source code generated on  : 06-Aug-2021 14:36:30
//

// Include Files
#include "ModelController.h"
#include <algorithm>
#include <cmath>

// Function Definitions
//
// Arguments    : void
// Return Type  : void
//
ModelController::ModelController()
{
  static const double dv[15]{0.06,
                             0.128,
                             0.22749999999999998,
                             0.118,
                             0.0363,
                             0.3,
                             0.29484,
                             0.165888,
                             0.152928,
                             10.0,
                             0.001,
                             0.0050866042499999988,
                             0.000905969664,
                             0.00070978982399999991,
                             0.1};
  static const double dv1[7]{
      0.1, 0.145, 0.236, 0.256, 0.355, 0.78539816339744828, 2.5132741228718345};
  for (int i{0}; i < 7; i++) {
    this->robot_dim[i] = dv1[i];
  }
  std::copy(&dv[0], &dv[15], &this->robot_inertial_par[0]);
  this->g = 9.81;
}

//
// Arguments    : void
// Return Type  : void
//
ModelController::~ModelController()
{
  // (no terminate code required)
}

//
// B_FEAS_CALC
//     B_FEAS =
//     B_FEAS_CALC(ALPHA,BETA,BETA_DOT,G,GAMMA,H1,H2,L_A,L_D,L_CM_C,L_CM_D,L_CM_AH,L_CM_BODY,L_H,M_AH,M_C,M_BODY,M_D,PHI_R,PHI_R_DOT,R_W,THETA_ST,THETA_ST_BODY)
//
// Arguments    : double alpha
//                double b_gamma
//                double h1
//                double h2
//                double phi_r
//                double beta
//                double phi_r_dot
//                double beta_dot
// Return Type  : double
//
double ModelController::b_feas_calc(double alpha, double b_gamma, double h1,
                                    double h2, double phi_r, double beta,
                                    double phi_r_dot, double beta_dot)
{
  double b_b_feas_tmp;
  double b_feas_tmp;
  double c_b_feas_tmp;
  double d_b_feas_tmp;
  double e_b_feas_tmp;
  double f_b_feas_tmp;
  double g_b_feas_tmp;
  double h_b_feas_tmp;
  double i_b_feas_tmp;
  double j_b_feas_tmp;
  double k_b_feas_tmp;
  double l_b_feas_tmp;
  double m_b_feas_tmp;
  double n_b_feas_tmp;
  double o_b_feas_tmp;
  double p_b_feas_tmp;
  double q_b_feas_tmp;
  double r_b_feas_tmp;
  double s_b_feas_tmp;
  double t15;
  double t16;
  double t17;
  double t20;
  double t22;
  double t23;
  double t4;
  double t5;
  double t6;
  double t7;
  double t8;
  double t9;
  //     This function was generated by the Symbolic Math Toolbox version 8.7.
  //     29-Jul-2021 17:21:23
  t4 = beta_dot * beta_dot;
  t5 = h1 * h1;
  t6 = h2 * h2;
  t7 = phi_r_dot * phi_r_dot;
  t8 = std::cos(alpha + b_gamma);
  t9 = std::sin(alpha + beta);
  t15 = std::cos((beta + this->robot_dim[5]) + this->robot_dim[6]);
  t16 = std::cos((b_gamma + phi_r) + this->robot_dim[5]);
  t17 = std::sin((beta + phi_r) + this->robot_dim[5]);
  t20 = std::cos(phi_r + -this->robot_dim[6]);
  t22 = std::cos((-alpha + this->robot_dim[5]) + this->robot_dim[6]);
  t23 = std::sin((phi_r + -alpha) + this->robot_dim[5]);
  b_feas_tmp = this->g * this->robot_dim[4];
  b_b_feas_tmp = this->robot_dim[3] * this->robot_inertial_par[9] *
                 this->robot_inertial_par[0];
  c_b_feas_tmp = this->robot_inertial_par[1] * this->robot_inertial_par[7] *
                 this->robot_inertial_par[0];
  d_b_feas_tmp = this->robot_dim[0] * this->robot_inertial_par[3] *
                 this->robot_inertial_par[8] * t4;
  e_b_feas_tmp = this->robot_inertial_par[3] * this->robot_dim[4] *
                 this->robot_inertial_par[8] * t4;
  f_b_feas_tmp = this->robot_inertial_par[1] * this->robot_dim[4] *
                 this->robot_inertial_par[7] * t4;
  g_b_feas_tmp = this->robot_dim[0] * this->robot_inertial_par[8] *
                 this->robot_inertial_par[0];
  h_b_feas_tmp = this->robot_inertial_par[2] * this->robot_inertial_par[6] *
                 this->robot_inertial_par[0];
  i_b_feas_tmp = this->robot_inertial_par[3] * this->robot_inertial_par[8] *
                 this->robot_inertial_par[0];
  j_b_feas_tmp = this->robot_dim[4] * this->robot_inertial_par[8] *
                 this->robot_inertial_par[0];
  k_b_feas_tmp = this->robot_dim[4] * this->robot_inertial_par[9] *
                 this->robot_inertial_par[0];
  l_b_feas_tmp = this->robot_dim[4] * this->robot_inertial_par[7] *
                 this->robot_inertial_par[0];
  m_b_feas_tmp = beta_dot * this->robot_dim[3];
  n_b_feas_tmp = beta_dot * this->robot_inertial_par[1];
  o_b_feas_tmp = beta_dot * h1;
  p_b_feas_tmp = beta_dot * h2;
  q_b_feas_tmp = o_b_feas_tmp * this->robot_dim[0];
  r_b_feas_tmp = p_b_feas_tmp * this->robot_inertial_par[3];
  s_b_feas_tmp = o_b_feas_tmp * this->robot_dim[4];
  return (((((((((((((((((((((((((((this->g * this->robot_dim[0] *
                                        this->robot_inertial_par[8] * t23 *
                                        -2.0 -
                                    this->g * this->robot_inertial_par[2] *
                                        this->robot_inertial_par[6] * t23 *
                                        2.0) +
                                   this->g * this->robot_inertial_par[3] *
                                       this->robot_inertial_par[8] * t16 *
                                       2.0) +
                                  this->g * this->robot_dim[3] *
                                      this->robot_inertial_par[9] * t17) +
                                 this->g * this->robot_inertial_par[1] *
                                     this->robot_inertial_par[7] * t17 * 2.0) -
                                this->g * this->robot_inertial_par[4] *
                                    this->robot_inertial_par[9] * t20) -
                               b_feas_tmp * this->robot_inertial_par[8] * t23 *
                                   2.0) -
                              b_feas_tmp * this->robot_inertial_par[9] * t23) -
                             b_feas_tmp * this->robot_inertial_par[7] * t23 *
                                 2.0) -
                            this->robot_dim[3] * this->robot_inertial_par[4] *
                                this->robot_inertial_par[9] * t4 * t15) +
                           this->robot_dim[3] * this->robot_dim[4] *
                               this->robot_inertial_par[9] * t4 * t9) +
                          f_b_feas_tmp * t9 * 2.0) -
                         g_b_feas_tmp * t7 * t23 * 2.0) -
                        h_b_feas_tmp * t7 * t23 * 2.0) +
                       i_b_feas_tmp * t7 * t16 * 2.0) +
                      b_b_feas_tmp * t4 * t17) +
                     b_b_feas_tmp * t7 * t17) +
                    c_b_feas_tmp * t4 * t17 * 2.0) +
                   c_b_feas_tmp * t7 * t17 * 2.0) -
                  this->robot_inertial_par[4] * this->robot_inertial_par[9] *
                      this->robot_inertial_par[0] * t7 * t20) -
                 j_b_feas_tmp * t7 * t23 * 2.0) -
                k_b_feas_tmp * t7 * t23) -
               l_b_feas_tmp * t7 * t23 * 2.0) -
              d_b_feas_tmp * t5 * t8 * 2.0) +
             d_b_feas_tmp * t6 * t8 * 2.0) -
            e_b_feas_tmp * t5 * t8 * 2.0) +
           e_b_feas_tmp * t6 * t8 * 2.0) +
          (((((((((((((((((((((-this->robot_dim[3] * this->robot_dim[4] *
                                   this->robot_inertial_par[9] * t4 * t5 * t9 -
                               f_b_feas_tmp * t5 * t9 * 2.0) +
                              this->robot_inertial_par[4] * this->robot_dim[4] *
                                  this->robot_inertial_par[9] * t4 * t5 * t22) -
                             g_b_feas_tmp * t4 * t5 * t23 * 2.0) -
                            h_b_feas_tmp * t4 * t5 * t23 * 2.0) +
                           i_b_feas_tmp * t4 * t6 * t16 * 2.0) -
                          j_b_feas_tmp * t4 * t5 * t23 * 2.0) -
                         k_b_feas_tmp * t4 * t5 * t23) -
                        l_b_feas_tmp * t4 * t5 * t23 * 2.0) -
                       m_b_feas_tmp * this->robot_inertial_par[4] *
                           this->robot_inertial_par[9] * phi_r_dot * t15 *
                           2.0) +
                      m_b_feas_tmp * this->robot_dim[4] *
                          this->robot_inertial_par[9] * phi_r_dot * t9 * 2.0) +
                     n_b_feas_tmp * this->robot_dim[4] *
                         this->robot_inertial_par[7] * phi_r_dot * t9 * 4.0) +
                    m_b_feas_tmp * this->robot_inertial_par[9] * phi_r_dot *
                        this->robot_inertial_par[0] * t17 * 2.0) +
                   n_b_feas_tmp * this->robot_inertial_par[7] * phi_r_dot *
                       this->robot_inertial_par[0] * t17 * 4.0) +
                  q_b_feas_tmp * this->robot_inertial_par[3] *
                      this->robot_inertial_par[8] * phi_r_dot * t8 * 4.0) +
                 p_b_feas_tmp * this->robot_dim[0] *
                     this->robot_inertial_par[3] * this->robot_inertial_par[8] *
                     phi_r_dot * t8 * 4.0) +
                o_b_feas_tmp * this->robot_inertial_par[3] *
                    this->robot_dim[4] * this->robot_inertial_par[8] *
                    phi_r_dot * t8 * 4.0) +
               r_b_feas_tmp * this->robot_dim[4] * this->robot_inertial_par[8] *
                   phi_r_dot * t8 * 4.0) +
              o_b_feas_tmp * this->robot_dim[3] * this->robot_dim[4] *
                  this->robot_inertial_par[9] * phi_r_dot * t9 * 2.0) +
             o_b_feas_tmp * this->robot_inertial_par[1] * this->robot_dim[4] *
                 this->robot_inertial_par[7] * phi_r_dot * t9 * 4.0) -
            o_b_feas_tmp * this->robot_inertial_par[4] * this->robot_dim[4] *
                this->robot_inertial_par[9] * phi_r_dot * t22 * 2.0) +
           q_b_feas_tmp * this->robot_inertial_par[8] * phi_r_dot *
               this->robot_inertial_par[0] * t23 * 4.0)) +
         ((((o_b_feas_tmp * this->robot_inertial_par[2] *
                 this->robot_inertial_par[6] * phi_r_dot *
                 this->robot_inertial_par[0] * t23 * 4.0 +
             r_b_feas_tmp * this->robot_inertial_par[8] * phi_r_dot *
                 this->robot_inertial_par[0] * t16 * 4.0) +
            s_b_feas_tmp * this->robot_inertial_par[8] * phi_r_dot *
                this->robot_inertial_par[0] * t23 * 4.0) +
           s_b_feas_tmp * this->robot_inertial_par[9] * phi_r_dot *
               this->robot_inertial_par[0] * t23 * 2.0) +
          s_b_feas_tmp * this->robot_inertial_par[7] * phi_r_dot *
              this->robot_inertial_par[0] * t23 * 4.0);
}

//
// File trailer for ModelController.cpp
//
// [EOF]
//
